mroonga/docker

Dockerfile/mysql5626_mroonga506/Dockerfile, Dockerfile/mysql5626_mroonga506/my.cnf, Dockerfile/mysql5627_mroonga508/Dockerfile, Dockerfile/mysql5627_mroonga508/my.cnf
=> Add my.cnf for character_set_server= utf8mb4

test/build.pl, test/cpanfile, test/version.json
=> Add version comparing from json file.

Dockerfile/mysql5627_mroonga509/Dockerfile, Dockerfile/mysql5627_mroonga509/my.cnf, test/version.json
Mroonga 5.09 has been released at 2015/10/29!
=> Add mysql5627_mroonga509

Dockerfile/mysql579_mroonga509/Dockerfile, Dockerfile/mysql579_mroonga509/my.cnf, test/version.json
MySQL 5.7 series generate temporary password automatically.
So added handling about auto-generated password in Dockerfile.
=> Add MySQL 5.7.9 + Mroonga 5.09

Dockerfile/mysql5627_mroonga510/Dockerfile, Dockerfile/mysql5627_mroonga510/my.cnf, test/version.json
Add MySQL 5.6.27 + Mroonga 5.10 image
=> Support mysql5627_mroonga510

Dockerfile/mysql579_mroonga510/Dockerfile, Dockerfile/mysql579_mroonga510/my.cnf, test/version.json
Add MySQL 5.7.9 + Mroonga 5.10 image.
=> Add mysql579_mroonga510

Dockerfile/mysql5628_mroonga511/Dockerfile, Dockerfile/mysql5628_mroonga511/entrypoint.sh, Dockerfile/mysql5628_mroonga511/my.cnf, test/version.json
mysql-community-mroonga-5.11 has been released.
=> Add mysql5628_mroonga511

Dockerfile/mysql5710_mroonga511/Dockerfile, Dockerfile/mysql5710_mroonga511/entrypoint.sh, Dockerfile/mysql5710_mroonga511/my.cnf, test/version.json
mysql57-community-mroonga-5.11 has been released.
=> Add mysql5710_mroonga511

Dockerfile/mysql5628_mroonga512/Dockerfile, Dockerfile/mysql5628_mroonga512/entrypoint.sh, Dockerfile/mysql5628_mroonga512/my.cnf, Dockerfile/mysql5710_mroonga512/Dockerfile, Dockerfile/mysql5710_mroonga512/entrypoint.sh, Dockerfile/mysql5710_mroonga512/my.cnf, test/version.json
Add mysql5710_mroonga512 and mysql5628_mroonga512.
groonga/mroonga:latest points mysql5628_mroonga512.
=> Add mroonga512

Dockerfile/mysql5629_mroonga600/Dockerfile, Dockerfile/mysql5629_mroonga600/entrypoint.sh, Dockerfile/mysql5629_mroonga600/my.cnf, test/version.json
=> Support mysql5629_mroonga600

Dockerfile/mysql5711_mroonga600/Dockerfile, Dockerfile/mysql5711_mroonga600/entrypoint.sh, Dockerfile/mysql5711_mroonga600/my.cnf, test/version.json
mysql57-community-mroonga-6.00 has been released.
=> Support mysql5711_mroonga600

Dockerfile/mysql5629_mroonga601/Dockerfile, Dockerfile/mysql5629_mroonga601/entrypoint.sh, Dockerfile/mysql5629_mroonga601/my.cnf, README.md, test/version.json
Add MySQL 5.6.29 + Mroonga 6.01
=> Add mysql5629_mroonga601

Dockerfile/mysql5711_mroonga601/Dockerfile, Dockerfile/mysql5711_mroonga601/entrypoint.sh, Dockerfile/mysql5711_mroonga601/my.cnf, README.md, test/version.json
Add MySQL 5.7.11 + Mroonga 6.01
=> Add mysql5711_mroonga601

Dockerfile/mysql5631_mroonga605/Dockerfile, Dockerfile/mysql5631_mroonga605/entrypoint.sh, Dockerfile/mysql5631_mroonga605/my.cnf, README.md, test/version.json
=> Add MySQL 5.6.31 + Mroonga 6.05 + Groonga 6.0.5

Dockerfile/mysql5713_mroonga605/Dockerfile, Dockerfile/mysql5713_mroonga605/entrypoint.sh, Dockerfile/mysql5713_mroonga605/my.cnf, README.md, test/version.json
=> Add MySQL 5.7.13 + Mroonga 6.05 + Groonga 6.0.5

Dockerfile/mysql5631_mroonga606/Dockerfile, Dockerfile/mysql5631_mroonga606/entrypoint.sh, Dockerfile/mysql5631_mroonga606/my.cnf, README.md, test/version.json
=> MySQL 5.6.31 + Mroonga 6.06 + Groonga 6.0.5

Dockerfile/mysql5713_mroonga606/Dockerfile, Dockerfile/mysql5713_mroonga606/entrypoint.sh, Dockerfile/mysql5713_mroonga606/my.cnf, README.md, test/version.json
=> MySQL 5.7.13 + Mroonga 6.06 + Groonga 6.0.5

Dockerfile/mysql5632_mroonga607/Dockerfile, Dockerfile/mysql5632_mroonga607/entrypoint.sh, Dockerfile/mysql5632_mroonga607/my.cnf, README.md, test/version.json
Mroonga 6.07 released at 2016/8/5!
=> Add mysql5632_mroonga607

Dockerfile/mysql5714_mroonga607/Dockerfile, Dockerfile/mysql5714_mroonga607/entrypoint.sh, Dockerfile/mysql5714_mroonga607/my.cnf, README.md, test/version.json
=> Add mysql5714_mroonga607

Dockerfile/mysql5632_mroonga608/Dockerfile, Dockerfile/mysql5632_mroonga608/entrypoint.sh, Dockerfile/mysql5632_mroonga608/my.cnf, README.md, test/version.json
Mroonga 6.08 has been released 2016/8/29!
=> Add mysql5632_mroonga608

Dockerfile/mysql5714_mroonga608/Dockerfile, Dockerfile/mysql5714_mroonga608/entrypoint.sh, Dockerfile/mysql5714_mroonga608/my.cnf, README.md, test/version.json
Mroonga 6.08 has been released at 2016/8/29
=> Add MySQL 5.7.14 + Mroonga 6.08

Dockerfile/mysql5633_mroonga609/Dockerfile, Dockerfile/mysql5633_mroonga609/entrypoint.sh, Dockerfile/mysql5633_mroonga609/my.cnf, Dockerfile/mysql5715_mroonga609/Dockerfile, Dockerfile/mysql5715_mroonga609/entrypoint.sh, Dockerfile/mysql5715_mroonga609/my.cnf, README.md, test/version.json
Mroonga 6.09 and Groonga 6.0.9 has been released 2016/09/29!
=> Add Mroonga 6.09 + MySQL 5.6.33, 5.7.15

Dockerfile/mysql5634_mroonga610/Dockerfile, Dockerfile/mysql5634_mroonga610/entrypoint.sh, Dockerfile/mysql5634_mroonga610/my.cnf, Dockerfile/mysql5716_mroonga610/Dockerfile, Dockerfile/mysql5716_mroonga610/entrypoint.sh, Dockerfile/mysql5716_mroonga610/my.cnf, README.md, test/version.json
Mroonga 6.10 has been released 2016/10/29!
=> Add Mroonga 6.10 with MySQL 5.6.34 and 5.7.16

Dockerfile/mysql5634_mroonga611/Dockerfile, Dockerfile/mysql5634_mroonga611/entrypoint.sh, Dockerfile/mysql5634_mroonga611/my.cnf, Dockerfile/mysql5716_mroonga611/Dockerfile, Dockerfile/mysql5716_mroonga611/entrypoint.sh, Dockerfile/mysql5716_mroonga611/my.cnf, README.md, test/version.json
Mroonga 6.11 has been released at 2016/11/29!
=> Add Mroonga 6.11

Dockerfile/mysql5635_mroonga613/Dockerfile, Dockerfile/mysql5635_mroonga613/entrypoint.sh, Dockerfile/mysql5635_mroonga613/my.cnf, Dockerfile/mysql5717_mroonga613/Dockerfile, Dockerfile/mysql5717_mroonga613/entrypoint.sh, Dockerfile/mysql5717_mroonga613/my.cnf, README.md, test/version.json
Mroonga 6.13 has been released at 2017/01/13!
=> Add mroonga613

Dockerfile/mysql5635_mroonga700/Dockerfile, Dockerfile/mysql5635_mroonga700/entrypoint.sh, Dockerfile/mysql5635_mroonga700/my.cnf, Dockerfile/mysql5717_mroonga700/Dockerfile, Dockerfile/mysql5717_mroonga700/entrypoint.sh, Dockerfile/mysql5717_mroonga700/my.cnf, README.md, test/version.json
Mroonga 7.00 has been released 2017/02/09!
=> Add Mroonga 7.00

Dockerfile/mysql5635_mroonga701/Dockerfile, Dockerfile/mysql5635_mroonga701/entrypoint.sh, Dockerfile/mysql5635_mroonga701/my.cnf, Dockerfile/mysql5717_mroonga701/Dockerfile, Dockerfile/mysql5717_mroonga701/entrypoint.sh, Dockerfile/mysql5717_mroonga701/my.cnf, README.md, test/version.json
Mroonga 7.01 had been released 2017/3/29!
=> Add Mroonga 7.01

Dockerfile/mysql5636_mroonga702/Dockerfile, Dockerfile/mysql5636_mroonga702/entrypoint.sh, Dockerfile/mysql5636_mroonga702/my.cnf, Dockerfile/mysql5718_mroonga702/Dockerfile, Dockerfile/mysql5718_mroonga702/entrypoint.sh, Dockerfile/mysql5718_mroonga702/my.cnf, README.md, test/version.json
Mronnga7.02 has been released at 4/29
=> add Mroonga7.02

Dockerfile/mysql5636_mroonga703/Dockerfile, Dockerfile/mysql5636_mroonga703/entrypoint.sh, Dockerfile/mysql5636_mroonga703/my.cnf, Dockerfile/mysql5718_mroonga703/Dockerfile, Dockerfile/mysql5718_mroonga703/entrypoint.sh, Dockerfile/mysql5718_mroonga703/my.cnf, README.md, test/version.json
Mroonga7.03 has been released 5/29
=> Add Mroonga7.03

Dockerfile/mysql5637_mroonga706/Dockerfile, Dockerfile/mysql5637_mroonga706/entrypoint.sh, Dockerfile/mysql5637_mroonga706/my.cnf, Dockerfile/mysql5719_mroonga706/Dockerfile, Dockerfile/mysql5719_mroonga706/entrypoint.sh, Dockerfile/mysql5719_mroonga706/my.cnf, README.md, test/version.json
=> Add mroonga706

.github/workflows/build.yml, test/build.sh
Changed `test/build.sh` to also test on already built images.
=> ci: Test the built image

.github/workflows/build.yml, README.md, test.sh
Test by specifying a built image.
=> Change test scripts to test only
